<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>System Information</title>

    <!-- Custom Stylesheets -->
    <link rel="stylesheet" href="assets/scss/settings.css">
    <!-- <link rel="stylesheet" href="assets/scss/mediaquery.css"> -->

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="assets/img/logos/kkis.ico">
</head>

<body>
    <div class="expanded d-none d-lg-flex">
        <?php
        include "settings.php";
        ?>
    </div>

    <div class="mainContainer" id="mainPanel">
        <div class="container-fluid content">
            <a href="./settings">
                <i role="button" class="backIcon fa-solid fa-arrow-left d-lg-none me-3" style="color: #9fa7bf"></i>
                <span class="sideTitle">System Information</span>
            </a>
            
            <div class="sectionDiv">
               <!-- CONTENT STARTS HERE -->
               <div class="row">
                    <div class="col-lg-4">
                        <span class="question">Why was the system created?</span>
                    </div>

                    <div class="col-lg-8" style="display:flex; align-items:center">
                        <p align="justify">The project team's program required them to create a system in order for them 
                            to graduate. And to do that, it is vital for the team to have a client. Upon 
                            consultation with the client, they have come with the agreement to develop the 
                            Katipunan ng Kabataan Information System. This system provided a modern solution 
                            to the lack of a consolidated and updated database that contains relevant information 
                            about the youth and residents of Barangay Sampiruhan, Calamba City.</p>
                    </div>
               </div>
            </div>

            <div class="sectionDiv">
                <!-- CONTENT STARTS HERE -->
                <div class="row">
                     <div class="col-lg-4">
                         <span class="question">What is the system all about?</span>
                     </div>
 
                     <div class="col-lg-8" style="display:flex; align-items:center">
                         <p align="justify">Katipunan ng Kabataan Information System is a web-based data management and 
                            document generation system that supports QR codes that are responsive to mobile phones and 
                            laptops. It aims to help the Sangguniang Kabataan in Barangay Sampiruhan, Calamba City, Laguna 
                            to address their problem in the manual processing of documents and services. The objective of 
                            this system is to digitize the processing of documents and to automate barangay services and 
                            transactions. The lack of an affordable system that could provide accuracy, accountability, 
                            and efficiency in SK activities or responses, motivated the project team to develop this system. 
                            Thus, having this system gives the SK officials ease when managing transaction processes.</p>
                     </div>
                </div>
             </div>

             <div class="sectionDiv">
                <!-- CONTENT STARTS HERE -->
                <div class="row">
                     <div class="col-lg-4">
                         <span class="question">What is the scope of the system?</span>
                     </div>
 
                     <div class="col-lg-8" style="display:flex; align-items:center">
                         <p align="justify">The team developed a QR code-supported, web-based information system that speeds 
                            up document transactions with guaranteed data integrity. This information system is an integrated 
                            set of components that collect, store, and process data and provide information, knowledge, and 
                            digital products. The QR codes generated by the system were printed along with their resident ID 
                            cards. This helps with the resident verification and smoother processing of relief aids and other 
                            government-issued projects. This significantly affected the barangay residents, SK Officials who 
                            were in charge of it, and the barangay itself. The barangay's file system procedures changed due 
                            to the system's implementation: Katipunan ng Kabataan Information System, guaranteed data confidentiality, 
                            integrity, and availability.</p>
                     </div>
                </div>
             </div>

             <div class="sectionDiv">
                <!-- CONTENT STARTS HERE -->
                <div class="row">
                     <div class="col-lg-4">
                         <span class="question">System Compatability</span>
                     </div>

                     <div class="col-lg-8">
                        <table class="compatability">
                            <tr>
                                <td rowspan="2"><p class="device">Desktop or laptop:</p></td>
                                <td>Windows (7,8,10,11)</td>
                            </tr>
                            <tr>
                                <td>macOS (Monterey to Sierra) Intel i3 3.5 GHz or Higher</td>
                            </tr>
            
                            <tr>
                                <td rowspan="2"><p class="device">Smartphone:</p></td>
                                <td>Android</td> 
                            </tr>
                            <tr>
                                <td>iOS</td>
                            </tr>
                        </table>
                     </div>
                </div>
             </div>

             


        </div>
    </div>

    <!-- Custom Script -->
    <script type="text/javascript" src="assets/js/settings.js"></script>

    <!-- Active page -->
    <script type="text/javascript">
        $(document).ready(function() {
            $("#systemInfo-link").addClass('active');
        });
    </script>
</body>

</html>